<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ViewComponents\**" />
    <Content Remove="ViewComponents\**" />
    <EmbeddedResource Remove="ViewComponents\**" />
    <None Remove="ViewComponents\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="dotenv.net" Version="4.0.0" />
    <PackageReference Include="Mapster" Version="10.0.7" />
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NicoPasino.Core\NicoPasino.Core.csproj" />
    <ProjectReference Include="..\NicoPasino.Infra\NicoPasino.Infra.csproj" />
    <ProjectReference Include="..\NicoPasino.Servicios\NicoPasino.Servicios.csproj" />
  </ItemGroup>

</Project>
