// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NicoPasino.Infra.Data;

#nullable disable

namespace NicoPasino.Infra.Migrations
{
    [DbContext(typeof(ventasdbContext))]
    partial class ventasdbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NicoPasino.Core.Modelos.Ventas.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Nombre" }, "nombre")
                        .IsUnique();

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("NicoPasino.Core.Modelos.Ventas.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit(1)")
                        .HasColumnName("activo")
                        .HasDefaultValueSql("b'1'");

                    b.Property<string>("Correo")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("correo");

                    b.Property<int>("Documento")
                        .HasColumnType("int")
                        .HasColumnName("documento");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fechaCreacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Correo" }, "correo")
                        .IsUnique();

                    b.HasIndex(new[] { "Documento" }, "documento")
                        .IsUnique();

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("NicoPasino.Core.Modelos.Ventas.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit(1)")
                        .HasColumnName("activo")
                        .HasDefaultValueSql("b'1'");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fechaCreacion");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fechaModificacion");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("idCategoria");

                    b.Property<int?>("IdPublica")
                        .HasColumnType("int")
                        .HasColumnName("idPublica");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("proveedor");

                    b.Property<int?>("StockMaximo")
                        .HasColumnType("int")
                        .HasColumnName("stockMaximo");

                    b.Property<int?>("StockMinimo")
                        .HasColumnType("int")
                        .HasColumnName("stockMinimo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCategoria" }, "idCategoria");

                    b.ToTable("producto", (string)null);
                });

            modelBuilder.Entity("NicoPasino.Core.Modelos.Ventas.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalle")
                        .HasColumnType("longtext")
                        .HasColumnName("detalle");

                    b.Property<DateTime?>("FechaVenta")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fechaVenta");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("idCliente");

                    b.Property<int?>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("numero");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCliente" }, "idCliente");

                    b.ToTable("venta", (string)null);
                });

            modelBuilder.Entity("NicoPasino.Core.Modelos.Ventas.Ventaporproducto", b =>
                {
                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("idVenta");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("idProducto");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("nombreProducto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precioUnitario");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("subTotal");

                    b.HasKey("IdVenta", "IdProducto")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "IdProducto" }, "idProducto");

                    b.ToTable("ventaporproducto", (string)null);
                });

            modelBuilder.Entity("NicoPasino.Core.Modelos.Ventas.Producto", b =>
                {
                    b.HasOne("NicoPasino.Core.Modelos.Ventas.Categoria", "IdCategoriaNavigation")
                        .WithMany("Producto")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("producto_ibfk_1");

                    b.Navigation("IdCategoriaNavigation");
                });

            modelBuilder.Entity("NicoPasino.Core.Modelos.Ventas.Venta", b =>
                {
                    b.HasOne("NicoPasino.Core.Modelos.Ventas.Cliente", "IdClienteNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("venta_ibfk_1");

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("NicoPasino.Core.Modelos.Ventas.Ventaporproducto", b =>
                {
                    b.HasOne("NicoPasino.Core.Modelos.Ventas.Producto", "IdProductoNavigation")
                        .WithMany("Ventaporproducto")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("ventaporproducto_ibfk_2");

                    b.HasOne("NicoPasino.Core.Modelos.Ventas.Venta", "IdVentaNavigation")
                        .WithMany("Ventaporproducto")
                        .HasForeignKey("IdVenta")
                        .IsRequired()
                        .HasConstraintName("ventaporproducto_ibfk_1");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("NicoPasino.Core.Modelos.Ventas.Categoria", b =>
                {
                    b.Navigation("Producto");
                });

            modelBuilder.Entity("NicoPasino.Core.Modelos.Ventas.Cliente", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("NicoPasino.Core.Modelos.Ventas.Producto", b =>
                {
                    b.Navigation("Ventaporproducto");
                });

            modelBuilder.Entity("NicoPasino.Core.Modelos.Ventas.Venta", b =>
                {
                    b.Navigation("Ventaporproducto");
                });
#pragma warning restore 612, 618
        }
    }
}
