// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NicoPasino.Core.Modelos.Ventas;

public partial class Cliente
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Correo { get; set; }

    public string Telefono { get; set; }

    public bool Activo { get; set; }

    public int Documento { get; set; }

    public virtual ICollection<Venta> Venta { get; set; } = new List<Venta>();

    public DateTime FechaCreacion { get; set; }

}