// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NicoPasino.Core.Modelos.Ventas;

public partial class Producto
{
    public int Id { get; set; }

    public int? IdPublica { get; set; }

    public int IdCategoria { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public int Cantidad { get; set; }

    public decimal Precio { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public bool Activo { get; set; }

    public int? StockMinimo { get; set; }

    public int? StockMaximo { get; set; }

    public string Proveedor { get; set; }

    public virtual Categoria IdCategoriaNavigation { get; set; }

    public virtual ICollection<Ventaporproducto> Ventaporproducto { get; set; } = new List<Ventaporproducto>();
}