// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NicoPasino.Core.Modelos.Ventas;

public partial class Ventaporproducto
{
    public int IdVenta { get; set; }

    public int IdProducto { get; set; }

    public int Cantidad { get; set; }

    public string NombreProducto { get; set; }

    public decimal PrecioUnitario { get; set; }

    public decimal SubTotal { get; set; }

    public virtual Producto IdProductoNavigation { get; set; }

    public virtual Venta IdVentaNavigation { get; set; }
}